Repository Ease-Attendance/Ease-Attendance, pull requests merged in 2021-03, with the labels that each got.

#89 Fix periods db
  .gitignore
  .idea/Zoom App Ease Attendance.iml
  .idea/jsLibraryMappings.xml
  public/dashboard.js
Labels: enhancement

#97 Public relation Change
  README.md
Labels: documentation

#96 Specify roster
  .idea/Zoom App Ease Attendance.iml
  .idea/jsLibraryMappings.xml
  .idea/runConfigurations/index_js.xml
  public/dashboard.css
  public/dashboard.html
  public/dashboard.js
Labels: enhancement

#108 Add a message to email support
  public/verify.css
  public/verify.html
  public/verify.js
Labels: bug, enhancement

#112 Add a filter icon with a drop down instead of all the filter buttons
  public/dashboard.css
  public/dashboard.html
  public/dashboard.js
Labels: enhancement

#115 Remove email verification
  index.js
  public/auth.js
  public/authRedirect.js
  public/dashboard.html
  public/dashboard.js
  public/login.html
  public/signup.html
  public/verify.css
  public/verify.html
  public/verify.js
Labels: enhancement
